### ISSUE TITLE
Same log printed in .log file as in .crash file

### ISSUE THREAD

**Issue by paultnp** [Jsonmess/Crasher#1]
After doing the given steps, same log printed in the .log file that was there in .crash file. What is the difference and what is the benefit of using this tool.

**Comment by Jsonmess** [comment]
1.do you  put .crash file and .dSYM in same folder？
2.Please  be sure  .crash UUID is the same as .DSYM file (it's contain UUID). or can not be parsed successfully 。

**Comment by paultnp** [comment]
Thanks Jsonmess
